### ISSUE TITLE
[BUG] (Spark 2.4.5) Pulsar receiver requires DataFrame creation before readStream/writeStream methods can be used

### ISSUE THREAD

**Issue by cogitoNLelouche** [streamnative/pulsar-spark#37]
**Describe the bug**
The spark-submit of a spark job written with the connector fails if a DataFrame is not created prior to calling readStream and writeStream. 

**To Reproduce**
1. Write a pyspark program that streams data from pulsar using `readStream` and writes somewhere using `writeStream`, see example code below.
2. Attempt to spark-submit using `./bin/spark-submit --master "local[*]" --packages io.streamnative.connectors:pulsar-spark-connector_${SCALA_VERSION}:${SPARK_VERSION} --repositories https://dl.bintray.com/streamnative/maven <your-script>`
3. If a `createDataFrame` using the SparkSession is not executed, the job will inevitably fail with error
``` 
py4j.protocol.Py4JJavaError: An error occurred while calling o34.load.
: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.apache.spark.sql.pulsar.PulsarProvider$.org$apache$spark$sql$pulsar$PulsarProvider$$jsonOptions(PulsarProvider.scala:603)
	at org.apache.spark.sql.pulsar.PulsarProvider.createMicroBatchReader(PulsarProvider.scala:154)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
The spark job does NOT need a DataFrame or other to be instantiated in order to run.

**Example failing python code**
```
import sys
from pyspark.sql import SparkSession

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("""
        Usage: TestPyspark.py <service_url> <admin_url> <topics>
        """, file=sys.stderr)
        sys.exit(-1)

    serviceUrl = sys.argv[1]
    adminUrl = sys.argv[2]
    topics = sys.argv[3]

    spark = SparkSession\
        .builder\
        .appName("StructuredPulsarWordCount")\
        .getOrCreate()

    # Create DataSet representing the stream of input lines from pulsar
    lines = spark\
        .readStream\
        .format("pulsar")\
        .option("service.url", serviceUrl)\
        .option("admin.url", adminUrl)\
        .option("topics", topics)\
        .load()\
        .selectExpr("CAST(value AS STRING)")

    query = lines\
        .writeStream\
        .outputMode('append')\
        .format('console')\
        .start()

    query.awaitTermination()
```

**Example working python code**
```
import sys
from pyspark.sql import SparkSession

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("""
        Usage: TestPyspark.py <service_url> <admin_url> <topics>
        """, file=sys.stderr)
        sys.exit(-1)
    serviceUrl = sys.argv[1]
    adminUrl = sys.argv[2]
    topics = sys.argv[3]

    spark = SparkSession\
        .builder\
        .appName("StructuredPulsarWordCount")\
        .getOrCreate()

    dt = spark.createDataFrame([(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0), (5, 12.0)], ("id", "v"))

    # Create DataSet representing the stream of input lines from pulsar
    lines = spark\
        .readStream\
        .format("pulsar")\
        .option("service.url", serviceUrl)\
        .option("admin.url", adminUrl)\
        .option("topics", topics)\
        .load()\
        .selectExpr("CAST(value AS STRING)")

    query = lines\
        .writeStream\
        .outputMode('append')\
        .format('console')\
        .start()

    query.awaitTermination()
```

**Additional context**
Using Spark 2.4.5
Using Python 3.7.3

**Comment by syhily** [comment]
We don't support pyspark now. I prefer to close this one for in favor of https://github.com/streamnative/pulsar-spark/issues/74
